name: calcul
description: Simple calculation without exponentiation.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  audioplayers: ^6.1.0
  dart_eval: ^0.7.10
  window_manager: ^0.4.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/